---
abstract: 'convert HTML to plain text'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: HTML::HTML5::ToText
name: HTML-HTML5-ToText
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  HTML::HTML5::Parser: 0.108
  List::Util: 0
  Moose: 0
  MooseX::Traits: 0
  POSIX: 0
  Text::Wrap: 0
  XML::LibXML::PrettyPrint: 0
  common::sense: 0
  namespace::autoclean: 0
  perl: 5.10.0
  utf8: 0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=HTML-HTML5-ToText
  homepage: https://metacpan.org/release/HTML-HTML5-ToText
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-html-html5-totext
version: 0.002
